version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login --username $DOCKER_NAME --password $DOCKER_PASSWORD
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $DOCKER_PROJECT:$DOCKER_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $DOCKER_PROJECT:$DOCKER_TAG