version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login --username $DOCKER_NAME --password $DOCKER_PASSWORD
      - sudo systemctl start docker
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t vladyslavkorzun/consumer:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/vladyslavkorzun/consumer:latest